# Generated by Django 5.0.4 on 2024-04-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Cédula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=250)),
                ('Apellido', models.CharField(max_length=250)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
