# Generated by Django 5.0.4 on 2024-04-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Cédula',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
